version: "3.9"
services:
  api:
    build:
      context: .
    image: devops-app:local
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=src
    volumes:
      - ./src:/app/src
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload